"""Trace the supplied Betfair logo (tools/art/ref/betfair-logo.png — black on
yellow) into vector path data for the printed pack art.

    python tools/art/trace_logo.py   →  tools/art/betfair-logo.js

The bitmap is upsampled 4× before thresholding so the contours land between
source pixels, traced with holes (the counters of b, e, a), simplified to a
fraction of a source pixel, and written as one even-odd SVG path in source-pixel
units, cropped to the logo's own bounding box. Needs OpenCV + NumPy.
"""
import os
import cv2
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "ref", "betfair-logo.png")
OUT = os.path.join(HERE, "betfair-logo.js")
UP = 4  # supersampling factor

img = cv2.imread(SRC, cv2.IMREAD_COLOR)
lum = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY).astype(np.float32)
big = cv2.resize(lum, None, fx=UP, fy=UP, interpolation=cv2.INTER_CUBIC)
# a light blur (~0.6 source px) irons out the source's compression nubs without
# rounding the arrow corners visibly
big = cv2.GaussianBlur(big, (0, 0), 0.6 * UP)
# ink is dark on a bright yellow field: split halfway between the two
ink_lv, bg_lv = np.percentile(lum, 2), np.percentile(lum, 60)
mask = (big < (ink_lv + bg_lv) / 2).astype(np.uint8) * 255
mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((5, 5), np.uint8))
mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((5, 5), np.uint8))

contours, hier = cv2.findContours(mask, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
keep = [c for c in contours if cv2.contourArea(c) > 6 * UP * UP]
xs = np.concatenate([c[:, 0, 0] for c in keep]); ys = np.concatenate([c[:, 0, 1] for c in keep])
x0, y0, x1, y1 = xs.min(), ys.min(), xs.max(), ys.max()

parts = []
for c in keep:
    # 0.35 source px: straight runs collapse to their corners, curves keep their shape
    poly = cv2.approxPolyDP(c, 0.35 * UP, True)[:, 0, :]
    pts = [((x - x0) / UP, (y - y0) / UP) for x, y in poly]
    parts.append("M" + "L".join(f"{x:.2f} {y:.2f}".replace(".00", "") for x, y in pts) + "Z")

w, h = (x1 - x0) / UP, (y1 - y0) / UP
with open(OUT, "w", newline="\n") as f:
    f.write("// betfair-logo.js — GENERATED by tools/art/trace_logo.py from ref/betfair-logo.png.\n")
    f.write("// The Betfair lockup (the two-arrow mark + the wordmark) as one even-odd path in a\n")
    f.write(f"// {w:.1f} × {h:.1f} box (source pixels). Fill with ctx.fill(new Path2D(d), \"evenodd\").\n")
    f.write(f"export const BETFAIR_LOGO = {{ w: {w:.2f}, h: {h:.2f}, d: \"{''.join(parts)}\" }};\n")
print(f"{len(keep)} contours, {sum(p.count('L') + 1 for p in parts)} points, box {w:.1f}x{h:.1f}, {os.path.getsize(OUT) // 1024} KB")
